// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import EditController from "./edit_controller"
application.register("edit", EditController)

import FormController from "./form_controller"
application.register("form", FormController)

import ModalConfirmationToDestroyController from "./modal_confirmation_to_destroy_controller"
application.register("modal-confirmation-to-destroy", ModalConfirmationToDestroyController)

import SearchPatientsController from "./search_patients_controller"
application.register("search-patients", SearchPatientsController)

import SeeAllController from "./see_all_controller"
application.register("see-all", SeeAllController)

import StarController from "./star_controller"
application.register("star", StarController)
